In [1]:
import numpy as np
import pandas as pd

In [6]:
data=pd.read_csv('play_tennis.csv')

In [7]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [8]:
data.drop(columns=['day'],inplace=True)

In [9]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [ ]:
# problem 1

# outlook = SUnny, Temp=Hot, Humidity=High, WInd=Weak
# Play or NO play?

In [ ]:
# SOlution

# P(Yes | Sunny,Hot,High,Weak)=P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) * P(Yes)

# P(No | Sunny,Hot,High,Weak)=P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)

In [12]:
# Training

# Lookup Table (DIctionary)

# Testing

In [13]:
# P(Yes)
# P(No)
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [14]:
py=9/14
pn=5/14
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [15]:
# Outlook

pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [16]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [17]:
# Outlook

pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [ ]:
pcn=1/5
phn=2/5
pmn=2/5

pcy=3/9
phy=2/9
pmy=4/9

In [19]:
# Outlook

pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [20]:
phighn=4/5
pnormaln=1/5

phighy=3/9
pnormaly=6/9

In [21]:
# Outlook

pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [22]:
pstrongn=3/5
pweakn=2/5

pstrongy=3/9
pweaky=6/9

In [23]:
# outlook = SUnny, Temp=Hot, Humidity=High, WInd=Weak

pyes= py * psy * phy * phighy * pweaky
pno= pn * psn * phn * phighn * pweakn

In [24]:
print(pyes)
print(pno)

0.007054673721340388
0.02742857142857143

In [25]:
# NO PLAY